---

- name: Reset MAX_MAP_COUNT as inside container - do the change on host!
  lineinfile:
    dest: /etc/default/elasticsearch
    regexp: '^MAX_MAP_COUNT=.*'
    line: 'MAX_MAP_COUNT='
    backup: yes
  notify: restart elasticsearch
  when: >
    ansible_os_family == 'Debian' and
    (ansible_virtualization_type == 'docker' or
      ansible_virtualization_type == 'lxc' or
      ansible_virtualization_type == 'openvz'
    )

- name: update ES_JAVA_OPTS settings
  lineinfile:
    dest: /etc/default/elasticsearch
    regexp: '^ES_JAVA_OPTS=.*'
    line: "ES_JAVA_OPTS=\"{{ elasticsearch_es_java_opts }}\""
    backup: yes
  notify: restart elasticsearch
  when: elasticsearch_es_java_opts is defined and elasticsearch_es_java_opts
